### ISSUE TITLE
Swerve drive modules follow target even if target is 360+

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/1721-RapidReact#26]
If the module falls behind the target heading it keeps spinning, this is mainly due to the target increasing even if it rotates a full rotatio ahead of the actual.

@KhanSimeoni has a way to fix this, if the target leads the actual by more than 1 rotatation, use mod to remove the rotation, ie if the target is 640 degrees, and the current pose is 120 degrees, the new target will be truncated to 280

**Comment by Kredcool** [comment]
isn't this bug fixed here or is this code not working?

`if self.angleSum - (2 * math.pi) > self.radians:
     self.angleSum = self.angleSum - (2 * math.pi)
 elif self.angleSum + (2 * math.pi) < self.radians:
      self.angleSum = self.angleSum + (2 * math.pi) `

**Comment by KenwoodFox** [comment]
afaik this is not fixed, though khan did some work on it. I think he did it in the simulation branch, so it either needs to be migrated out of there, or the simulation branch needs to be cleaned up.

Id recomend you move that code or fix this again in your own branch to keep things clean @Kredcool

**Comment by KhanSimeoni** [comment]
The fix was done in the bugfix/swerve branch, and was tested to work with the prototype swerve module. It should work as far as I know

**Comment by KenwoodFox** [comment]
> The fix was done in the bugfix/swerve branch, and was tested to work with the prototype swerve module. It should work as far as I know

Lets do a quick test today and close this if its all done, if it was fixed in bugfix/swerve thats good.

**Comment by KenwoodFox** [comment]
closed in favor of #37
